import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth } = Dimensions.get('window');

export const blogStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  featuredSection: {
    backgroundColor: '#F5F5F5',
    paddingTop: 8,
    paddingBottom: 16,
  },
  featuredScroll: {
    paddingLeft: 16,
  },
  featuredCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  featuredImage: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  featuredContent: {
    padding: 16,
  },
  featuredTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  featuredDescription: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 20,
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D0D0D0',
  },
  activeDot: {
    backgroundColor: '#3DD5DC',
    width: 24,
  },
  section: {
    paddingVertical: 16,
    backgroundColor: '#F5F5F5',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
  },
  seeMoreText: {
    fontSize: 14,
    color: '#3DD5DC',
    fontWeight: '600',
  },
  youtubeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  youtubeButtonText: {
    fontSize: 14,
    color: '#3DD5DC',
    fontWeight: '600',
  },
  horizontalScroll: {
    paddingLeft: 16,
    paddingRight: 16,
    gap: 16,
  },
  blogCard: {
    width: screenWidth * 0.75,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  blogImage: {
    width: '100%',
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  blogContent: {
    padding: 12,
  },
  blogCategory: {
    fontSize: 12,
    color: '#999999',
    marginBottom: 4,
  },
  blogTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 6,
  },
  blogDescription: {
    fontSize: 13,
    color: '#666666',
    marginBottom: 8,
    lineHeight: 18,
  },
  blogMeta: {
    fontSize: 12,
    color: '#999999',
  },
  videoCard: {
    width: screenWidth * 0.8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  videoThumbnail: {
    width: '100%',
    height: 180,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
  },
  videoOverlayText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 12,
    textAlign: 'center',
  },
  videoContent: {
    padding: 12,
  },
  videoCategory: {
    fontSize: 11,
    color: '#3DD5DC',
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  videoTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  youtubeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  youtubeTagText: {
    fontSize: 11,
    color: '#FF0000',
    fontWeight: '500',
  },
  videoMeta: {
    fontSize: 12,
    color: '#999999',
  },
  reportCard: {
    marginHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 12,
  },
  reportContent: {
    flex: 1,
    marginRight: 12,
  },
  reportTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 6,
  },
  reportDescription: {
    fontSize: 13,
    color: '#666666',
    marginBottom: 8,
  },
  reportDate: {
    fontSize: 12,
    color: '#999999',
  },
  reportImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hrCard: {
    width: screenWidth * 0.85,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  hrImage: {
    width: '100%',
    height: 180,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  hrOverlayText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 12,
    textAlign: 'center',
  },
  hrContent: {
    padding: 12,
  },
  hrCategory: {
    fontSize: 12,
    color: '#999999',
    marginBottom: 4,
  },
  hrTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 6,
  },
  hrMeta: {
    fontSize: 12,
    color: '#999999',
  },
});
