import { StyleSheet } from "react-native";

export const welcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#3DD5DC",
  },
  illustrationContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  illustration: {
    width: "100%",
    height: "100%",
    maxWidth: 400,
    maxHeight: 350,
  },
  contentContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingHorizontal: 30,
    paddingTop: 40,
    paddingBottom: 50,
    minHeight: "45%",
    alignItems: "center",
  },
  appName: {
    fontSize: 32,
    fontFamily: "Poppins_700Bold",
    color: "#3DD5DC",
    letterSpacing: 2,
    marginBottom: 15,
  },
  title: {
    fontSize: 24,
    fontFamily: "Poppins_600SemiBold",
    color: "#000000",
    textAlign: "center",
    marginBottom: 15,
    lineHeight: 32,
  },
  description: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 30,
  },
  button: {
    backgroundColor: "#3DD5DC",
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 80,
    shadowColor: "#3DD5DC",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontFamily: "Poppins_600SemiBold",
  },
  exploreButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#3DD5DC",
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 70,
    marginTop: 15,
  },
  exploreButtonText: {
    color: "#3DD5DC",
    fontSize: 18,
    fontFamily: "Poppins_600SemiBold",
  },
});
